### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [klahnakoski/Bugzilla-ETL#4]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by klahnakoski** [comment]
Thank you for pointing out this oversight of mine.  I added the license to the v2 and master branches (and it will eventually spread to the other branches as they get merged)

If you plan to use this code, then I suggest the master branch for the sake of stability.
