### ISSUE TITLE
Docker container doesn't properly set PYTHONPATH prior to executing

### ISSUE THREAD

**Issue by ckolos** [klahnakoski/Bugzilla-ETL#9]
On https://github.com/mozilla/Bugzilla-ETL/blob/v0.11/resources/docker/etl.dockerfile#L43, the environment isn't being set properly to execute the specified command.

I suggest one of the following:
1) Change this line to the following:
```
CMD export PYTHONPATH=.:vendor \
      && python bzETL/bz_etl.py --settings=resources/docker/config.json
```
2) Switch the default command for the container to execute the resources/docker/etl.sh script
```
RUN chmod 755 /app/resources/docker/etl.sh
CMD /app/resources/docker/etl.sh
```

Either works; The second would allow additional ENV vars to be set if needed.

**Comment by ckolos** [comment]
This is still not correct in v0.13

**Comment by klahnakoski** [comment]
Sorry for the delay, I am working on this

**Comment by klahnakoski** [comment]
Please try this https://circleci.com/gh/mozilla/Bugzilla-ETL/125

**Comment by klahnakoski** [comment]
I think this is fixed
